### ISSUE TITLE
How should syntax highlight be specified?

### ISSUE THREAD

**Issue by dandv** [telerik/kendo-docs#574]
[Another](https://github.com/telerik/kendo-docs/issues/573) thing to mention in the README (or in the [authoring guidelines Wiki](https://github.com/telerik/kendo-docs/wiki/Code-Examples), though those pages were easy to skip from the README): how syntax highlight is specified / what Mardkown flavor/parser is used. Will GitHub-flavored Markdown work?

    ```css
        #GridID > table /* header + data table */
        {
            table-layout: fixed;
        }
    ```

Asking because,

1. On docs.telerik.com, the CSS examples [on this page](http://docs.telerik.com/kendo-ui/web/grid/walkthrough#column-widths) are highlighted as if `#` marks the start of a comment.
2. GitHub doesn't have syntax highlight information to display the example code with syntax highlight - see e.g. https://github.com/telerik/kendo-docs/blob/master/api/javascript/ui/grid.md - all examples lack syntax highlight.
