### ISSUE TITLE
Overriding TreeView's expand/collapse icons should not include the loader image

### ISSUE THREAD

**Issue by dandv** [telerik/kendo-docs#602]
[This forum thread](http://www.telerik.com/forums/how-do-i-set-icon-for-expand-and-collapse) explains how to override the expand/collapse icons for the TreeView.

The problem is that this rule will also affect the loader image, whose class is `k-icon k-plus k-loading`:

```css
.k-treeview .k-plus {
    background: url("customExpandedIcon.png") center center;
}
```

Two solutions:

1. Set the class for the loading image to just `k-icon k-loading`, since there's no more `k-plus` anyway.
2. (Quick and dirty): Update that forum thread response to exclude the `k-loading` class:

```css
.k-treeview .k-plus:not(.k-loading) {
    background: url("customExpandedIcon.png") center center;
}
```

I would post the solution in that thread, but don't have permission.
